name: CI

on:
  pull_request:
    branches: [main]

jobs:
  check_deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: gh-action-rl-protect-scan
        uses: reversinglabs/gh-action-rl-protect-scan@v1
        id: rl-protect
        env:
          RL_TOKEN: ${{ secrets.RL_TOKEN }}
        with:
          scan-path: 'package.json'
          scan-profile: 'baseline'
          report: 'rl-protect-report.json'
          check-deps: 'develop,release'
          log-file: 'rl-protect.txt'
          log-level: 'pass'
          verbose: true

      - name: Run a multi-line script to show the result of the rl-protect action
        run: |
            echo "Status of rl-protect: ${{steps.rl-protect.outputs.status}}"
            echo "Description of rl-protect: ${{steps.rl-protect.outputs.description}}"
            ls -la
            exit 0
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 10.27.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint

      - run: pnpm test
